#!/bin/bash

/usr/local/bin/gpio -g mode 17 up

messagesent=false
today=$(date +%Y%m%d)
preamble="Initial Startup - $(date +%Y/%m/%d_%H:%M) - "

while $true
do

  res=$(/usr/local/bin/gpio -g read 17)

  if [ $res == 1 ]
  then
      if [ "${today}" == "$(date +%Y%m%d)" ]
      then
        if ! ${messagesent}
        then
          if (( $(date +%H) > 8 ))
          then
            now=$(date +%s)
            while [ $res == 1 ]
            do
              res=$(/usr/local/bin/gpio -g read 17)
              sleep 0.1
            done
            while [ $res == 0 ]
            do
              res=$(/usr/local/bin/gpio -g read 17)
              sleep 0.1
            done
            if (( $(($(date +%s)-now))<20))
            then
              messagesent=true
              echo ${preamble}Movement at Elmstead - $(date +%H:%M) | /usr/bin/sendxmpp -t -u john275 -o gmail.com cherylbucke
              preamble=""
            fi
          fi
        fi
      else
        today=$(date +%Y%m%d)
        messagesent=false
      fi
  fi

  sleep 0.1

done
