#!/bin/bash

server=server

export EYAML_CONFIG=$(echo pkcs7_private_key: $HOME/keys/private_key.pkcs7.pem;echo pkcs7_public_key: $HOME/keys/public_key.pkcs7.pem)

xmacaddress=$(eyaml decrypt -s $(grep 'server::xmacaddress:' $HOME/facts.eyaml | awk '{print $2}'))
broadcastaddress=$(eyaml decrypt -s $(grep 'home::subnet::broadcastaddress:' $HOME/facts.eyaml | awk '{print $2}'))

$(curl --connect-timeout 5 ${server}:22 2> /dev/null | grep -q ^SSH)
resp=$?

if ((${resp}==1))
then
	wolhplocal.py ${xmacaddress} ${broadcastaddress}
fi

while ((${resp}==1))
do
	sleep 10
	$(curl --connect-timeout 5 ${server}:22 2> /dev/null | grep -q ^SSH)
	resp=$?
done

ssh -X ${server}
